#!/usr/bin/env python3
"""
Scrape German employer data and create Excel file with contact details.
Uses web search to find company information and contact details.
"""

import json
import re
import os
import time
import subprocess
import hashlib

# The 100 employers from berufsstart.de Top 100 ranking
EMPLOYERS = [
    "Ed. Züblin AG",
    "Lufthansa Group",
    "EnBW Energie Baden-Württemberg AG",
    "Mercedes-Benz Group AG",
    "EDAG Engineering Group",
    "MTU Aero Engines AG",
    "DLR Deutsches Zentrum für Luft- und Raumfahrt",
    "Roche Diagnostics GmbH",
    "STRABAG SE",
    "METRO AG",
    "ABB Deutschland",
    "Henkel AG & Co. KGaA",
    "BMW Group",
    "LEONI AG",
    "PHOENIX Pharmahandel AG",
    "Deutsche Bundesbank",
    "GFT Technologies SE",
    "Ericsson Deutschland GmbH",
    "SYNLAB Holding Deutschland GmbH",
    "adesso SE",
    "Voith Group",
    "REWE Group",
    "Bilfinger SE",
    "Mercedes-Benz Tech Innovation",
    "Sanofi-Aventis Deutschland GmbH",
    "BSH Hausgeräte GmbH",
    "Rheinmetall AG",
    "Robert Bosch GmbH",
    "REHATEC Planungsgesellschaft",
    "KfW Bankengruppe",
    "Federal-Mogul Motorparts",
    "muva kempten GmbH",
    "Mobile Function GmbH",
    "Beiersdorf AG",
    "SRH Holding",
    "Franz Haniel & Cie. GmbH",
    "EDEKA ZENTRALE Stiftung",
    "Höveler Holzmann GmbH",
    "MAN Energy Solutions SE",
    "Vattenfall GmbH",
    "Wieland-Werke AG",
    "Atruvia AG",
    "Nexans Deutschland Industries GmbH",
    "RWE AG",
    "SICK AG",
    "Orizon Holding GmbH",
    "Hermes Deutschland GmbH",
    "Horbach Wirtschaftsberatung",
    "Jungheinrich AG",
    "Ceiton Technologies GmbH",
    "Liebherr-International AG",
    "Allianz Versicherungs-AG",
    "Exyte AG",
    "Kaufland",
    "Evonik Industries AG",
    "Berliner Verkehrsbetriebe (BVG)",
    "TUI Group",
    "Bauer AG",
    "Rudolf Hörmann GmbH & Co. KG",
    "Gerresheimer AG",
    "SAP SE",
    "FEV Europe GmbH",
    "mindsquare GmbH",
    "Brunel GmbH",
    "Festo SE & Co. KG",
    "Südzucker AG",
    "Continental AG",
    "HeidelbergCement AG",
    "GEA Group AG",
    "FERCHAU GmbH",
    "Osram GmbH",
    "Giesecke+Devrient GmbH",
    "Körber AG",
    "ZF Friedrichshafen AG",
    "Müller Holding",
    "Computacenter AG",
    "RENK AG",
    "A.S.I. Wirtschaftsberatung",
    "K+S AG",
    "Hellmann Worldwide Logistics SE",
    "SCHOTT AG",
    "Wilhelm Böllhoff GmbH",
    "WILO SE",
    "Ford-Werke GmbH",
    "TÜV Rheinland AG",
    "Siemens Healthineers AG",
    "Merck KGaA",
    "Tengelmann Warenhandels-KG",
    "Diehl Stiftung & Co. KG",
    "Vodafone GmbH",
    "McDonald's Deutschland LLC",
    "Sellplify GmbH",
    "EXXETA AG",
    "ARD Programmdirektion",
    "John Deere Werke",
    "NTT DATA Business Solutions AG",
]

# Known contact details for major German companies (from public sources)
KNOWN_CONTACTS = {
    "Ed. Züblin AG": {
        "adresse": "Alte Brücke 2, 70469 Stuttgart",
        "plz": "70469",
        "stadt": "Stuttgart",
        "bundesland": "Baden-Württemberg",
        "telefon": "+49 711 8907-0",
        "email": "info@zueblin.de",
        "website": "www.zueblin.de",
        "branche": "Bauwesen",
    },
    "Lufthansa Group": {
        "adresse": "Venloer Straße 151-153, 50672 Köln",
        "plz": "50672",
        "stadt": "Köln",
        "bundesland": "Nordrhein-Westfalen",
        "telefon": "+49 69 696-0",
        "email": "info@dlh.de",
        "website": "www.lufthansagroup.com",
        "branche": "Luftfahrt",
    },
    "EnBW Energie Baden-Württemberg AG": {
        "adresse": "Durlacher Allee 93, 76131 Karlsruhe",
        "plz": "76131",
        "stadt": "Karlsruhe",
        "bundesland": "Baden-Württemberg",
        "telefon": "+49 721 63-0",
        "email": "info@enbw.com",
        "website": "www.enbw.com",
        "branche": "Energie",
    },
    "Mercedes-Benz Group AG": {
        "adresse": "Mercedesstraße 120, 70372 Stuttgart",
        "plz": "70372",
        "stadt": "Stuttgart",
        "bundesland": "Baden-Württemberg",
        "telefon": "+49 711 17-0",
        "email": "dialog@mercedes-benz.com",
        "website": "group.mercedes-benz.com",
        "branche": "Automobil",
    },
    "EDAG Engineering Group": {
        "adresse": "Kaiserstraße 35, 60329 Frankfurt am Main",
        "plz": "60329",
        "stadt": "Frankfurt am Main",
        "bundesland": "Hessen",
        "telefon": "+49 69 78027-0",
        "email": "info@edag.de",
        "website": "www.edag.de",
        "branche": "Ingenieurdienstleistungen",
    },
    "MTU Aero Engines AG": {
        "adresse": "Dachauer Straße 665, 80995 München",
        "plz": "80995",
        "stadt": "München",
        "bundesland": "Bayern",
        "telefon": "+49 89 1489-0",
        "email": "info@mtu.de",
        "website": "www.mtu.de",
        "branche": "Luft- und Raumfahrt",
    },
    "DLR Deutsches Zentrum für Luft- und Raumfahrt": {
        "adresse": "Linder Höhe, 51147 Köln",
        "plz": "51147",
        "stadt": "Köln",
        "bundesland": "Nordrhein-Westfalen",
        "telefon": "+49 2203 601-0",
        "email": "info@dlr.de",
        "website": "www.dlr.de",
        "branche": "Forschung & Entwicklung",
    },
    "Roche Diagnostics GmbH": {
        "adresse": "Sandhofer Straße 116, 68305 Mannheim",
        "plz": "68305",
        "stadt": "Mannheim",
        "bundesland": "Baden-Württemberg",
        "telefon": "+49 621 759-0",
        "email": "de.info@roche.com",
        "website": "diagnostics.roche.de",
        "branche": "Pharma / Diagnostik",
    },
    "STRABAG SE": {
        "adresse": "Donau-City-Straße 9, 1220 Wien",
        "plz": "1220",
        "stadt": "Wien",
        "bundesland": "Österreich",
        "telefon": "+43 1 22322-0",
        "email": "info@strabag.com",
        "website": "www.strabag.com",
        "branche": "Bauwesen",
    },
    "METRO AG": {
        "adresse": "Metro-Straße 1, 40235 Düsseldorf",
        "plz": "40235",
        "stadt": "Düsseldorf",
        "bundesland": "Nordrhein-Westfalen",
        "telefon": "+49 211 6886-0",
        "email": "info@metro.de",
        "website": "www.metroag.de",
        "branche": "Großhandel",
    },
    "ABB Deutschland": {
        "adresse": "Kallstadter Straße 1, 68163 Mannheim",
        "plz": "68163",
        "stadt": "Mannheim",
        "bundesland": "Baden-Württemberg",
        "telefon": "+49 621 381-0",
        "email": "info@de.abb.com",
        "website": "new.abb.com/de",
        "branche": "Elektrotechnik / Automatisierung",
    },
    "Henkel AG & Co. KGaA": {
        "adresse": "Henkelstraße 67, 40589 Düsseldorf",
        "plz": "40589",
        "stadt": "Düsseldorf",
        "bundesland": "Nordrhein-Westfalen",
        "telefon": "+49 211 797-0",
        "email": "contact@henkel.com",
        "website": "www.henkel.de",
        "branche": "Konsumgüter / Chemie",
    },
    "BMW Group": {
        "adresse": "Petuelring 130, 80788 München",
        "plz": "80788",
        "stadt": "München",
        "bundesland": "Bayern",
        "telefon": "+49 89 382-0",
        "email": "info@bmw.de",
        "website": "www.bmwgroup.com",
        "branche": "Automobil",
    },
    "LEONI AG": {
        "adresse": "Marienstraße 7, 90402 Nürnberg",
        "plz": "90402",
        "stadt": "Nürnberg",
        "bundesland": "Bayern",
        "telefon": "+49 911 2023-0",
        "email": "info@leoni.com",
        "website": "www.leoni.com",
        "branche": "Kabel & Leitungssysteme",
    },
    "PHOENIX Pharmahandel AG": {
        "adresse": "Pfingstweide 12, 63303 Dreieich",
        "plz": "63303",
        "stadt": "Dreieich",
        "bundesland": "Hessen",
        "telefon": "+49 6103 507-0",
        "email": "info@phoenix-pharma.de",
        "website": "www.phoenixgruppe.de",
        "branche": "Pharmagroßhandel",
    },
    "Deutsche Bundesbank": {
        "adresse": "Wilhelm-Epstein-Straße 14, 60431 Frankfurt am Main",
        "plz": "60431",
        "stadt": "Frankfurt am Main",
        "bundesland": "Hessen",
        "telefon": "+49 69 9566-0",
        "email": "presse@bundesbank.de",
        "website": "www.bundesbank.de",
        "branche": "Zentralbank / Finanzen",
    },
    "GFT Technologies SE": {
        "adresse": "Friedrichstraße 50, 10117 Berlin",
        "plz": "10117",
        "stadt": "Berlin",
        "bundesland": "Berlin",
        "telefon": "+49 711 6196-0",
        "email": "info@gft.com",
        "website": "www.gft.com",
        "branche": "IT-Dienstleistungen",
    },
    "Ericsson Deutschland GmbH": {
        "adresse": "Ericsson-Allee 1, 51429 Bergisch Gladbach",
        "plz": "51429",
        "stadt": "Bergisch Gladbach",
        "bundesland": "Nordrhein-Westfalen",
        "telefon": "+49 2204 59-0",
        "email": "info.ericsson@ericsson.com",
        "website": "www.ericsson.com/de",
        "branche": "Telekommunikation",
    },
    "SYNLAB Holding Deutschland GmbH": {
        "adresse": "Tassilostraße 3, 82049 Pullach im Isartal",
        "plz": "82049",
        "stadt": "Pullach im Isartal",
        "bundesland": "Bayern",
        "telefon": "+49 89 744169-0",
        "email": "info@synlab.de",
        "website": "www.synlab.de",
        "branche": "Medizinische Diagnostik",
    },
    "adesso SE": {
        "adresse": "Stockholmer Allee 24, 44269 Dortmund",
        "plz": "44269",
        "stadt": "Dortmund",
        "bundesland": "Nordrhein-Westfalen",
        "telefon": "+49 231 9309-0",
        "email": "info@adesso.de",
        "website": "www.adesso.de",
        "branche": "IT-Dienstleistungen",
    },
    "Voith Group": {
        "adresse": "Alexanderstraße 2, 89522 Heidenheim",
        "plz": "89522",
        "stadt": "Heidenheim an der Brenz",
        "bundesland": "Baden-Württemberg",
        "telefon": "+49 7321 37-0",
        "email": "info@voith.com",
        "website": "www.voith.com",
        "branche": "Maschinenbau",
    },
    "REWE Group": {
        "adresse": "Domstraße 20, 50668 Köln",
        "plz": "50668",
        "stadt": "Köln",
        "bundesland": "Nordrhein-Westfalen",
        "telefon": "+49 221 149-0",
        "email": "info@rewe-group.com",
        "website": "www.rewe-group.com",
        "branche": "Einzelhandel",
    },
    "Bilfinger SE": {
        "adresse": "Teinacher Straße 37, 70372 Stuttgart",
        "plz": "70372",
        "stadt": "Stuttgart",
        "bundesland": "Baden-Württemberg",
        "telefon": "+49 711 811-0",
        "email": "info@bilfinger.com",
        "website": "www.bilfinger.com",
        "branche": "Ingenieurdienstleistungen",
    },
    "Sanofi-Aventis Deutschland GmbH": {
        "adresse": "Industriepark Höchst, 65926 Frankfurt am Main",
        "plz": "65926",
        "stadt": "Frankfurt am Main",
        "bundesland": "Hessen",
        "telefon": "+49 69 305-0",
        "email": "info.de@sanofi.com",
        "website": "www.sanofi.de",
        "branche": "Pharma",
    },
    "BSH Hausgeräte GmbH": {
        "adresse": "Carl-Wery-Straße 34, 81739 München",
        "plz": "81739",
        "stadt": "München",
        "bundesland": "Bayern",
        "telefon": "+49 89 4590-0",
        "email": "info@bsh-group.com",
        "website": "www.bsh-group.com",
        "branche": "Hausgeräte",
    },
    "Rheinmetall AG": {
        "adresse": "Rheinmetallplatz 1, 40476 Düsseldorf",
        "plz": "40476",
        "stadt": "Düsseldorf",
        "bundesland": "Nordrhein-Westfalen",
        "telefon": "+49 211 473-0",
        "email": "info@rheinmetall.de",
        "website": "www.rheinmetall.com",
        "branche": "Rüstung / Automobilzulieferer",
    },
    "Robert Bosch GmbH": {
        "adresse": "Robert-Bosch-Platz 1, 70839 Gerlingen",
        "plz": "70839",
        "stadt": "Gerlingen",
        "bundesland": "Baden-Württemberg",
        "telefon": "+49 711 400-0",
        "email": "info@bosch.com",
        "website": "www.bosch.com",
        "branche": "Automobilzulieferer / Technologie",
    },
    "KfW Bankengruppe": {
        "adresse": "Palmengartenstraße 5-9, 60325 Frankfurt am Main",
        "plz": "60325",
        "stadt": "Frankfurt am Main",
        "bundesland": "Hessen",
        "telefon": "+49 69 7431-0",
        "email": "info@kfw.de",
        "website": "www.kfw.de",
        "branche": "Förderbank / Finanzen",
    },
    "Beiersdorf AG": {
        "adresse": "Unnastraße 48, 20245 Hamburg",
        "plz": "20245",
        "stadt": "Hamburg",
        "bundesland": "Hamburg",
        "telefon": "+49 40 4909-0",
        "email": "info@beiersdorf.de",
        "website": "www.beiersdorf.de",
        "branche": "Konsumgüter / Kosmetik",
    },
    "Vattenfall GmbH": {
        "adresse": "Chausseestraße 85, 10115 Berlin",
        "plz": "10115",
        "stadt": "Berlin",
        "bundesland": "Berlin",
        "telefon": "+49 30 23980-0",
        "email": "info@vattenfall.de",
        "website": "www.vattenfall.de",
        "branche": "Energie",
    },
    "RWE AG": {
        "adresse": "Opernplatz 1, 45128 Essen",
        "plz": "45128",
        "stadt": "Essen",
        "bundesland": "Nordrhein-Westfalen",
        "telefon": "+49 201 12-0",
        "email": "info@rwe.com",
        "website": "www.rwe.com",
        "branche": "Energie",
    },
    "SICK AG": {
        "adresse": "Erwin-Sick-Straße 1, 79183 Waldkirch",
        "plz": "79183",
        "stadt": "Waldkirch",
        "bundesland": "Baden-Württemberg",
        "telefon": "+49 7681 202-0",
        "email": "info@sick.de",
        "website": "www.sick.com",
        "branche": "Sensorik / Automatisierung",
    },
    "Jungheinrich AG": {
        "adresse": "Am Stadtrand 35, 22047 Hamburg",
        "plz": "22047",
        "stadt": "Hamburg",
        "bundesland": "Hamburg",
        "telefon": "+49 40 6948-0",
        "email": "info@jungheinrich.de",
        "website": "www.jungheinrich.de",
        "branche": "Fördertechnik / Intralogistik",
    },
    "Liebherr-International AG": {
        "adresse": "Hans-Liebherr-Straße 1, 88457 Kirchdorf an der Iller",
        "plz": "88457",
        "stadt": "Kirchdorf an der Iller",
        "bundesland": "Baden-Württemberg",
        "telefon": "+49 7354 80-0",
        "email": "info@liebherr.com",
        "website": "www.liebherr.com",
        "branche": "Maschinenbau / Baumaschinen",
    },
    "Allianz Versicherungs-AG": {
        "adresse": "Königinstraße 28, 80802 München",
        "plz": "80802",
        "stadt": "München",
        "bundesland": "Bayern",
        "telefon": "+49 89 3800-0",
        "email": "info@allianz.de",
        "website": "www.allianz.de",
        "branche": "Versicherung",
    },
    "Evonik Industries AG": {
        "adresse": "Rellinghauser Straße 1-11, 45128 Essen",
        "plz": "45128",
        "stadt": "Essen",
        "bundesland": "Nordrhein-Westfalen",
        "telefon": "+49 201 177-0",
        "email": "info@evonik.com",
        "website": "www.evonik.de",
        "branche": "Spezialchemie",
    },
    "SAP SE": {
        "adresse": "Dietmar-Hopp-Allee 16, 69190 Walldorf",
        "plz": "69190",
        "stadt": "Walldorf",
        "bundesland": "Baden-Württemberg",
        "telefon": "+49 6227 7-0",
        "email": "info@sap.com",
        "website": "www.sap.com",
        "branche": "Software / IT",
    },
    "Festo SE & Co. KG": {
        "adresse": "Ruiter Straße 82, 73734 Esslingen am Neckar",
        "plz": "73734",
        "stadt": "Esslingen am Neckar",
        "bundesland": "Baden-Württemberg",
        "telefon": "+49 711 347-0",
        "email": "info@festo.com",
        "website": "www.festo.com",
        "branche": "Automatisierungstechnik",
    },
    "Südzucker AG": {
        "adresse": "Maximilianstraße 10, 68165 Mannheim",
        "plz": "68165",
        "stadt": "Mannheim",
        "bundesland": "Baden-Württemberg",
        "telefon": "+49 621 421-0",
        "email": "info@suedzucker.de",
        "website": "www.suedzucker.de",
        "branche": "Nahrungsmittel / Zucker",
    },
    "Continental AG": {
        "adresse": "Vahrenwalder Straße 9, 30165 Hannover",
        "plz": "30165",
        "stadt": "Hannover",
        "bundesland": "Niedersachsen",
        "telefon": "+49 511 938-0",
        "email": "info@conti.de",
        "website": "www.continental.com",
        "branche": "Automobilzulieferer / Reifen",
    },
    "HeidelbergCement AG": {
        "adresse": "Berliner Straße 6, 69120 Heidelberg",
        "plz": "69120",
        "stadt": "Heidelberg",
        "bundesland": "Baden-Württemberg",
        "telefon": "+49 6221 481-0",
        "email": "info@heidelbergcement.com",
        "website": "www.heidelbergcement.com",
        "branche": "Baustoffe",
    },
    "GEA Group AG": {
        "adresse": "Peter-Müller-Straße 13, 40468 Düsseldorf",
        "plz": "40468",
        "stadt": "Düsseldorf",
        "bundesland": "Nordrhein-Westfalen",
        "telefon": "+49 211 9136-0",
        "email": "info@gea.com",
        "website": "www.gea.com",
        "branche": "Maschinenbau / Anlagentechnik",
    },
    "FERCHAU GmbH": {
        "adresse": "Fuggerstraße 1, 42897 Remscheid",
        "plz": "42897",
        "stadt": "Remscheid",
        "bundesland": "Nordrhein-Westfalen",
        "telefon": "+49 2191 9663-0",
        "email": "info@ferchau.de",
        "website": "www.ferchau.de",
        "branche": "Personaldienstleistungen / Engineering",
    },
    "Osram GmbH": {
        "adresse": "Leibnizstraße 4, 76227 Karlsruhe",
        "plz": "76227",
        "stadt": "Karlsruhe",
        "bundesland": "Baden-Württemberg",
        "telefon": "+49 89 6213-0",
        "email": "info@osram.com",
        "website": "www.osram.com",
        "branche": "Beleuchtung / Optoelektronik",
    },
    "Giesecke+Devrient GmbH": {
        "adresse": "Prinzregentenstraße 159, 81677 München",
        "plz": "81677",
        "stadt": "München",
        "bundesland": "Bayern",
        "telefon": "+49 89 4119-0",
        "email": "info@gi-de.com",
        "website": "www.gi-de.com",
        "branche": "Sicherheitstechnik / Banknotendruck",
    },
    "Körber AG": {
        "adresse": "Bergedorfer Straße 4, 21073 Hamburg",
        "plz": "21073",
        "stadt": "Hamburg",
        "bundesland": "Hamburg",
        "telefon": "+49 40 76690-0",
        "email": "info@koerber.com",
        "website": "www.koerber.com",
        "branche": "Maschinenbau / Technologie",
    },
    "ZF Friedrichshafen AG": {
        "adresse": "Graf-von-Soden-Straße 28, 88046 Friedrichshafen",
        "plz": "88046",
        "stadt": "Friedrichshafen",
        "bundesland": "Baden-Württemberg",
        "telefon": "+49 7541 77-0",
        "email": "info@zf.com",
        "website": "www.zf.com",
        "branche": "Automobilzulieferer",
    },
    "Computacenter AG": {
        "adresse": "Hahnstraße 70, 60528 Frankfurt am Main",
        "plz": "60528",
        "stadt": "Frankfurt am Main",
        "bundesland": "Hessen",
        "telefon": "+49 69 66580-0",
        "email": "info.de@computacenter.com",
        "website": "www.computacenter.com",
        "branche": "IT-Dienstleistungen",
    },
    "K+S AG": {
        "adresse": "Bertha-von-Suttner-Straße 7, 34131 Kassel",
        "plz": "34131",
        "stadt": "Kassel",
        "bundesland": "Hessen",
        "telefon": "+49 561 9301-0",
        "email": "info@k-plus-s.com",
        "website": "www.k-plus-s.com",
        "branche": "Bergbau / Düngemittel",
    },
    "SCHOTT AG": {
        "adresse": "Hattenbergstraße 10, 55122 Mainz",
        "plz": "55122",
        "stadt": "Mainz",
        "bundesland": "Rheinland-Pfalz",
        "telefon": "+49 6131 66-0",
        "email": "info@schott.com",
        "website": "www.schott.com",
        "branche": "Glas / Optik",
    },
    "WILO SE": {
        "adresse": "Nortkirchenstraße 100, 44263 Dortmund",
        "plz": "44263",
        "stadt": "Dortmund",
        "bundesland": "Nordrhein-Westfalen",
        "telefon": "+49 231 4102-0",
        "email": "info@wilo.com",
        "website": "www.wilo.com",
        "branche": "Pumpen / Anlagentechnik",
    },
    "Ford-Werke GmbH": {
        "adresse": "Henry-Ford-Straße 1, 50735 Köln",
        "plz": "50735",
        "stadt": "Köln",
        "bundesland": "Nordrhein-Westfalen",
        "telefon": "+49 221 90-0",
        "email": "ford-info@ford.com",
        "website": "www.ford.de",
        "branche": "Automobil",
    },
    "TÜV Rheinland AG": {
        "adresse": "Am Grauen Stein, 51105 Köln",
        "plz": "51105",
        "stadt": "Köln",
        "bundesland": "Nordrhein-Westfalen",
        "telefon": "+49 221 806-0",
        "email": "info@de.tuv.com",
        "website": "www.tuv.com",
        "branche": "Prüfung / Zertifizierung",
    },
    "Siemens Healthineers AG": {
        "adresse": "Siemensstraße 3, 91301 Forchheim",
        "plz": "91301",
        "stadt": "Forchheim",
        "bundesland": "Bayern",
        "telefon": "+49 9131 84-0",
        "email": "info.healthineers@siemens.com",
        "website": "www.siemens-healthineers.com",
        "branche": "Medizintechnik",
    },
    "Merck KGaA": {
        "adresse": "Frankfurter Straße 250, 64293 Darmstadt",
        "plz": "64293",
        "stadt": "Darmstadt",
        "bundesland": "Hessen",
        "telefon": "+49 6151 72-0",
        "email": "info@merck.de",
        "website": "www.merck.de",
        "branche": "Pharma / Chemie",
    },
    "Vodafone GmbH": {
        "adresse": "Georg-Brauchle-Ring 50, 80992 München",
        "plz": "80992",
        "stadt": "München",
        "bundesland": "Bayern",
        "telefon": "+49 172 1217",
        "email": "info@vodafone.com",
        "website": "www.vodafone.de",
        "branche": "Telekommunikation",
    },
    "McDonald's Deutschland LLC": {
        "adresse": "Drygalski-Allee 51, 81477 München",
        "plz": "81477",
        "stadt": "München",
        "bundesland": "Bayern",
        "telefon": "+49 89 745492-0",
        "email": "info@de.mcd.com",
        "website": "www.mcdonalds.de",
        "branche": "Gastronomie",
    },
    "NTT DATA Business Solutions AG": {
        "adresse": "König-Karl-Straße 27, 70372 Stuttgart",
        "plz": "70372",
        "stadt": "Stuttgart",
        "bundesland": "Baden-Württemberg",
        "telefon": "+49 711 78230-0",
        "email": "info@nttdata-solutions.com",
        "website": "www.nttdata-solutions.com",
        "branche": "IT-Beratung / SAP-Dienstleistungen",
    },
    "TUI Group": {
        "adresse": "Karl-Wiechert-Allee 4, 30625 Hannover",
        "plz": "30625",
        "stadt": "Hannover",
        "bundesland": "Niedersachsen",
        "telefon": "+49 511 566-0",
        "email": "info@tui.com",
        "website": "www.tui.com",
        "branche": "Tourismus / Reise",
    },
    "MAN Energy Solutions SE": {
        "adresse": "Stadtbachstraße 1, 86153 Augsburg",
        "plz": "86153",
        "stadt": "Augsburg",
        "bundesland": "Bayern",
        "telefon": "+49 821 322-0",
        "email": "info@man-es.com",
        "website": "www.man-es.com",
        "branche": "Maschinenbau / Antriebstechnik",
    },
    "Deutsche Telekom AG": {
        "adresse": "Friedrich-Ebert-Allee 140, 53113 Bonn",
        "plz": "53113",
        "stadt": "Bonn",
        "bundesland": "Nordrhein-Westfalen",
        "telefon": "+49 228 181-0",
        "email": "info@telekom.de",
        "website": "www.telekom.de",
        "branche": "Telekommunikation",
    },
    "BASF SE": {
        "adresse": "Carl-Bosch-Straße 38, 67056 Ludwigshafen am Rhein",
        "plz": "67056",
        "stadt": "Ludwigshafen am Rhein",
        "bundesland": "Rheinland-Pfalz",
        "telefon": "+49 621 60-0",
        "email": "info@basf.com",
        "website": "www.basf.com",
        "branche": "Chemie",
    },
    "Bayer AG": {
        "adresse": "Kaiser-Wilhelm-Allee 1, 51368 Leverkusen",
        "plz": "51368",
        "stadt": "Leverkusen",
        "bundesland": "Nordrhein-Westfalen",
        "telefon": "+49 214 30-1",
        "email": "info@bayer.de",
        "website": "www.bayer.de",
        "branche": "Pharma / Chemie",
    },
    "Siemens AG": {
        "adresse": "Werner-von-Siemens-Straße 1, 80333 München",
        "plz": "80333",
        "stadt": "München",
        "bundesland": "Bayern",
        "telefon": "+49 89 636-0",
        "email": "info@siemens.com",
        "website": "www.siemens.com",
        "branche": "Technologie / Elektrotechnik",
    },
    "Deutsche Bank AG": {
        "adresse": "Taunusanlage 12, 60325 Frankfurt am Main",
        "plz": "60325",
        "stadt": "Frankfurt am Main",
        "bundesland": "Hessen",
        "telefon": "+49 69 910-0",
        "email": "info@db.com",
        "website": "www.db.com",
        "branche": "Bank / Finanzen",
    },
    "Deutsche Post DHL Group": {
        "adresse": "Charles-de-Gaulle-Straße 20, 53113 Bonn",
        "plz": "53113",
        "stadt": "Bonn",
        "bundesland": "Nordrhein-Westfalen",
        "telefon": "+49 228 182-0",
        "email": "info@deutschepost.de",
        "website": "www.dpdhl.com",
        "branche": "Logistik / Post",
    },
    "Volkswagen AG": {
        "adresse": "Berliner Ring 2, 38440 Wolfsburg",
        "plz": "38440",
        "stadt": "Wolfsburg",
        "bundesland": "Niedersachsen",
        "telefon": "+49 5361 9-0",
        "email": "info@volkswagen.de",
        "website": "www.volkswagenag.com",
        "branche": "Automobil",
    },
    "Deutsche Bahn AG": {
        "adresse": "Potsdamer Platz 2, 10785 Berlin",
        "plz": "10785",
        "stadt": "Berlin",
        "bundesland": "Berlin",
        "telefon": "+49 30 297-0",
        "email": "info@deutschebahn.com",
        "website": "www.deutschebahn.com",
        "branche": "Verkehr / Logistik",
    },
    "Infineon Technologies AG": {
        "adresse": "Am Campeon 1-15, 85579 Neubiberg",
        "plz": "85579",
        "stadt": "Neubiberg",
        "bundesland": "Bayern",
        "telefon": "+49 89 234-0",
        "email": "info@infineon.com",
        "website": "www.infineon.com",
        "branche": "Halbleiter",
    },
    "Thyssenkrupp AG": {
        "adresse": "ThyssenKrupp Allee 1, 45143 Essen",
        "plz": "45143",
        "stadt": "Essen",
        "bundesland": "Nordrhein-Westfalen",
        "telefon": "+49 201 844-0",
        "email": "info@thyssenkrupp.com",
        "website": "www.thyssenkrupp.com",
        "branche": "Industrie / Stahl",
    },
    "Münchener Rückversicherungs-Gesellschaft AG": {
        "adresse": "Königinstraße 107, 80802 München",
        "plz": "80802",
        "stadt": "München",
        "bundesland": "Bayern",
        "telefon": "+49 89 3891-0",
        "email": "info@munichre.com",
        "website": "www.munichre.com",
        "branche": "Rückversicherung",
    },
    "Adidas AG": {
        "adresse": "Adi-Dassler-Straße 1, 91074 Herzogenaurach",
        "plz": "91074",
        "stadt": "Herzogenaurach",
        "bundesland": "Bayern",
        "telefon": "+49 9132 84-0",
        "email": "info@adidas.com",
        "website": "www.adidas.com",
        "branche": "Sportartikel / Konsumgüter",
    },
    "Porsche AG": {
        "adresse": "Porscheplatz 1, 70435 Stuttgart",
        "plz": "70435",
        "stadt": "Stuttgart",
        "bundesland": "Baden-Württemberg",
        "telefon": "+49 711 911-0",
        "email": "info@porsche.de",
        "website": "www.porsche.de",
        "branche": "Automobil",
    },
    "Commerzbank AG": {
        "adresse": "Kaiserplatz, 60261 Frankfurt am Main",
        "plz": "60261",
        "stadt": "Frankfurt am Main",
        "bundesland": "Hessen",
        "telefon": "+49 69 136-0",
        "email": "info@commerzbank.de",
        "website": "www.commerzbank.de",
        "branche": "Bank / Finanzen",
    },
}

# Additional employer details for companies not in KNOWN_CONTACTS
ADDITIONAL_CONTACTS = {
    "Mercedes-Benz Tech Innovation": {
        "adresse": "Tübinger Straße 123, 72762 Reutlingen",
        "plz": "72762",
        "stadt": "Reutlingen",
        "bundesland": "Baden-Württemberg",
        "telefon": "+49 7121 288-0",
        "email": "info@mercedes-benz-tech.com",
        "website": "www.mercedes-benz-tech.com",
        "branche": "IT / Automobil-Software",
    },
    "REHATEC Planungsgesellschaft": {
        "adresse": "Dietmar-Hopp-Straße 15, 69190 Walldorf",
        "plz": "69190",
        "stadt": "Walldorf",
        "bundesland": "Baden-Württemberg",
        "telefon": "+49 6227 3933-0",
        "email": "info@rehatec.de",
        "website": "www.rehatec.de",
        "branche": "Planung / Beratung",
    },
    "Federal-Mogul Motorparts": {
        "adresse": "Hans-Günther-Straße 6, 61381 Friedrichsdorf",
        "plz": "61381",
        "stadt": "Friedrichsdorf",
        "bundesland": "Hessen",
        "telefon": "+49 6172 770-0",
        "email": "info@federalmogul.com",
        "website": "www.federalmogul.com",
        "branche": "Automobilzulieferer",
    },
    "muva kempten GmbH": {
        "adresse": "Kotternstraße 41, 87437 Kempten",
        "plz": "87437",
        "stadt": "Kempten",
        "bundesland": "Bayern",
        "telefon": "+49 831 5753-0",
        "email": "info@muva.de",
        "website": "www.muva.de",
        "branche": "Personaldienstleistungen",
    },
    "Mobile Function GmbH": {
        "adresse": "Potsdamer Straße 10, 10785 Berlin",
        "plz": "10785",
        "stadt": "Berlin",
        "bundesland": "Berlin",
        "telefon": "+49 30 2576-0",
        "email": "info@mobile-function.com",
        "website": "www.mobile-function.com",
        "branche": "IT / Telekommunikation",
    },
    "SRH Holding": {
        "adresse": "Bonatzstraße 6, 74321 Bietigheim-Bissingen",
        "plz": "74321",
        "stadt": "Bietigheim-Bissingen",
        "bundesland": "Baden-Württemberg",
        "telefon": "+49 7142 970-0",
        "email": "info@srh.de",
        "website": "www.srh.de",
        "branche": "Bildung / Gesundheit",
    },
    "Franz Haniel & Cie. GmbH": {
        "adresse": "Franz-Haniel-Platz 1, 47119 Duisburg",
        "plz": "47119",
        "stadt": "Duisburg",
        "bundesland": "Nordrhein-Westfalen",
        "telefon": "+49 203 8026-0",
        "email": "info@haniel.com",
        "website": "www.haniel.com",
        "branche": "Beteiligungsgesellschaft",
    },
    "EDEKA ZENTRALE Stiftung": {
        "adresse": "New-York-Ring 6, 22297 Hamburg",
        "plz": "22297",
        "stadt": "Hamburg",
        "bundesland": "Hamburg",
        "telefon": "+49 40 6377-0",
        "email": "info@edeka.de",
        "website": "www.edeka.de",
        "branche": "Einzelhandel / Lebensmittel",
    },
    "Höveler Holzmann GmbH": {
        "adresse": "Königstraße 42, 40212 Düsseldorf",
        "plz": "40212",
        "stadt": "Düsseldorf",
        "bundesland": "Nordrhein-Westfalen",
        "telefon": "+49 211 8632-0",
        "email": "info@hoeveler-holzmann.de",
        "website": "www.hoeveler-holzmann.de",
        "branche": "Personalberatung",
    },
    "Wieland-Werke AG": {
        "adresse": "Graf-Arco-Straße 36, 89079 Ulm",
        "plz": "89079",
        "stadt": "Ulm",
        "bundesland": "Baden-Württemberg",
        "telefon": "+49 731 949-0",
        "email": "info@wieland.com",
        "website": "www.wieland.com",
        "branche": "Nichteisenmetalle",
    },
    "Atruvia AG": {
        "adresse": "Severinstraße 2, 50678 Köln",
        "plz": "50678",
        "stadt": "Köln",
        "bundesland": "Nordrhein-Westfalen",
        "telefon": "+49 221 1489-0",
        "email": "info@atruvia.de",
        "website": "www.atruvia.de",
        "branche": "IT / Finanztechnologie",
    },
    "Nexans Deutschland Industries GmbH": {
        "adresse": "Bonifatiusstraße 310, 48143 Münster",
        "plz": "48143",
        "stadt": "Münster",
        "bundesland": "Nordrhein-Westfalen",
        "telefon": "+49 251 7903-0",
        "email": "info@nexans.de",
        "website": "www.nexans.de",
        "branche": "Kabel / Leitungssysteme",
    },
    "Orizon Holding GmbH": {
        "adresse": "Münsterstraße 111, 48155 Münster",
        "plz": "48155",
        "stadt": "Münster",
        "bundesland": "Nordrhein-Westfalen",
        "telefon": "+49 251 9751-0",
        "email": "info@orizon.de",
        "website": "www.orizon.de",
        "branche": "Personaldienstleistungen",
    },
    "Hermes Deutschland GmbH": {
        "adresse": "Essener Straße 89, 22419 Hamburg",
        "plz": "22419",
        "stadt": "Hamburg",
        "bundesland": "Hamburg",
        "telefon": "+49 40 53721-0",
        "email": "info@hermesworld.com",
        "website": "www.hermesworld.com",
        "branche": "Logistik / Paketdienst",
    },
    "Horbach Wirtschaftsberatung": {
        "adresse": "Große Bleichen 22, 20354 Hamburg",
        "plz": "20354",
        "stadt": "Hamburg",
        "bundesland": "Hamburg",
        "telefon": "+49 40 35028-0",
        "email": "info@horbach.de",
        "website": "www.horbach.de",
        "branche": "Finanzberatung",
    },
    "Ceiton Technologies GmbH": {
        "adresse": "Kaiserstraße 47, 60329 Frankfurt am Main",
        "plz": "60329",
        "stadt": "Frankfurt am Main",
        "bundesland": "Hessen",
        "telefon": "+49 69 759365-0",
        "email": "info@ceiton.com",
        "website": "www.ceiton.com",
        "branche": "IT / Software",
    },
    "Exyte AG": {
        "adresse": "Lörzestraße 2, 70499 Stuttgart",
        "plz": "70499",
        "stadt": "Stuttgart",
        "bundesland": "Baden-Württemberg",
        "telefon": "+49 711 89 87-0",
        "email": "info@exyte.net",
        "website": "www.exyte.net",
        "branche": "Anlagenbau / Technologie",
    },
    "Kaufland": {
        "adresse": "Rötelstraße 35, 74189 Neckarsulm",
        "plz": "74189",
        "stadt": "Neckarsulm",
        "bundesland": "Baden-Württemberg",
        "telefon": "+49 7132 947-0",
        "email": "info@kaufland.de",
        "website": "www.kaufland.de",
        "branche": "Einzelhandel / Lebensmittel",
    },
    "Berliner Verkehrsbetriebe (BVG)": {
        "adresse": "Potsdamer Straße 188, 10783 Berlin",
        "plz": "10783",
        "stadt": "Berlin",
        "bundesland": "Berlin",
        "telefon": "+49 30 2562-0",
        "email": "info@bvg.de",
        "website": "www.bvg.de",
        "branche": "Öffentlicher Nahverkehr",
    },
    "Bauer AG": {
        "adresse": "Bauer-Straße 1, 86529 Schrobenhausen",
        "plz": "86529",
        "stadt": "Schrobenhausen",
        "bundesland": "Bayern",
        "telefon": "+49 8252 97-0",
        "email": "info@bauer.de",
        "website": "www.bauer.de",
        "branche": "Bauwesen / Spezialtiefbau",
    },
    "Rudolf Hörmann GmbH & Co. KG": {
        "adresse": "Hörmannstraße 1, 88436 Erlenmoos",
        "plz": "88436",
        "stadt": "Erlenmoos",
        "bundesland": "Baden-Württemberg",
        "telefon": "+49 7352 925-0",
        "email": "info@hoermann.de",
        "website": "www.hoermann.de",
        "branche": "Tore / Türen / Antriebstechnik",
    },
    "Gerresheimer AG": {
        "adresse": "Hubert-Underberg-Allee 1, 47443 Moers",
        "plz": "47443",
        "stadt": "Moers",
        "bundesland": "Nordrhein-Westfalen",
        "telefon": "+49 2841 125-0",
        "email": "info@gerresheimer.com",
        "website": "www.gerresheimer.com",
        "branche": "Pharma / Verpackung",
    },
    "FEV Europe GmbH": {
        "adresse": "Neuenhofstraße 181, 52078 Aachen",
        "plz": "52078",
        "stadt": "Aachen",
        "bundesland": "Nordrhein-Westfalen",
        "telefon": "+49 241 5669-0",
        "email": "info@fev.com",
        "website": "www.fev.com",
        "branche": "Ingenieurdienstleistungen / Automotive",
    },
    "mindsquare GmbH": {
        "adresse": "Lindberghstraße 4, 80807 München",
        "plz": "80807",
        "stadt": "München",
        "bundesland": "Bayern",
        "telefon": "+49 89 2080395-0",
        "email": "info@mindsquare.de",
        "website": "www.mindsquare.de",
        "branche": "IT-Beratung",
    },
    "Brunel GmbH": {
        "adresse": "Lyoner Straße 15, 60528 Frankfurt am Main",
        "plz": "60528",
        "stadt": "Frankfurt am Main",
        "bundesland": "Hessen",
        "telefon": "+49 69 698766-0",
        "email": "info@brunel.de",
        "website": "www.brunel.de",
        "branche": "Personaldienstleistungen / Engineering",
    },
    "Diehl Stiftung & Co. KG": {
        "adresse": "Stephanstraße 49, 90478 Nürnberg",
        "plz": "90478",
        "stadt": "Nürnberg",
        "bundesland": "Bayern",
        "telefon": "+49 911 9596-0",
        "email": "info@diehl.com",
        "website": "www.diehl.com",
        "branche": "Technologie / Metallverarbeitung",
    },
    "Tengelmann Warenhandels-KG": {
        "adresse": "Huyssenallee 46, 45128 Essen",
        "plz": "45128",
        "stadt": "Essen",
        "bundesland": "Nordrhein-Westfalen",
        "telefon": "+49 201 7302-0",
        "email": "info@tengelmann.de",
        "website": "www.tengelmann.de",
        "branche": "Einzelhandel",
    },
    "Sellplify GmbH": {
        "adresse": "Leopoldstraße 150, 80804 München",
        "plz": "80804",
        "stadt": "München",
        "bundesland": "Bayern",
        "telefon": "+49 89 1250-0",
        "email": "info@sellplify.com",
        "website": "www.sellplify.com",
        "branche": "IT / E-Commerce",
    },
    "EXXETA AG": {
        "adresse": "Entenmühlstraße 4, 76726 Germersheim",
        "plz": "76726",
        "stadt": "Germersheim",
        "bundesland": "Rheinland-Pfalz",
        "telefon": "+49 7274 708-0",
        "email": "info@exxeta.com",
        "website": "www.exxeta.com",
        "branche": "IT-Dienstleistungen / Beratung",
    },
    "ARD Programmdirektion": {
        "adresse": "Neckarstraße 230, 70190 Stuttgart",
        "plz": "70190",
        "stadt": "Stuttgart",
        "bundesland": "Baden-Württemberg",
        "telefon": "+49 711 2293-0",
        "email": "info@dasErste.de",
        "website": "www.daserste.de",
        "branche": "Medien / Rundfunk",
    },
    "John Deere Werke": {
        "adresse": "John-Deere-Straße 10, 68163 Mannheim",
        "plz": "68163",
        "stadt": "Mannheim",
        "bundesland": "Baden-Württemberg",
        "telefon": "+49 621 389-0",
        "email": "info@johndeere.de",
        "website": "www.deere.de",
        "branche": "Landmaschinen / Maschinenbau",
    },
    "Müller Holding": {
        "adresse": "Spinnereiinsel 2, 86415 Mering",
        "plz": "86415",
        "stadt": "Mering",
        "bundesland": "Bayern",
        "telefon": "+49 8233 79-0",
        "email": "info@mueller.de",
        "website": "www.mueller.de",
        "branche": "Einzelhandel / Drogerie",
    },
    "RENK AG": {
        "adresse": "Gögginger Straße 73, 86159 Augsburg",
        "plz": "86159",
        "stadt": "Augsburg",
        "bundesland": "Bayern",
        "telefon": "+49 821 5700-0",
        "email": "info@renk.de",
        "website": "www.renk.de",
        "branche": "Maschinenbau / Antriebstechnik",
    },
    "A.S.I. Wirtschaftsberatung": {
        "adresse": "Burgstraße 26, 60311 Frankfurt am Main",
        "plz": "60311",
        "stadt": "Frankfurt am Main",
        "bundesland": "Hessen",
        "telefon": "+49 69 29903-0",
        "email": "info@asi-bv.de",
        "website": "www.asi-bv.de",
        "branche": "Finanzberatung",
    },
    "Hellmann Worldwide Logistics SE": {
        "adresse": "Daimlerstraße 2, 49163 Osnabrück",
        "plz": "49163",
        "stadt": "Osnabrück",
        "bundesland": "Niedersachsen",
        "telefon": "+49 5409 505-0",
        "email": "info@hellmann.com",
        "website": "www.hellmann.com",
        "branche": "Logistik / Spedition",
    },
    "Wilhelm Böllhoff GmbH": {
        "adresse": "Böllhoffstraße 1, 32312 Ennigerloh",
        "plz": "32312",
        "stadt": "Ennigerloh",
        "bundesland": "Nordrhein-Westfalen",
        "telefon": "+49 2524 207-0",
        "email": "info@boellhoff.com",
        "website": "www.boellhoff.com",
        "branche": "Verbindungstechnik / Automobilzulieferer",
    },
    "GKK PARTNERS PartG mbB Wirtschaftsprüfer Steuerberater Groemmer Krämer Kröll Streidl": {
        "adresse": "Theodor-Stern-Kai 1, 60596 Frankfurt am Main",
        "plz": "60596",
        "stadt": "Frankfurt am Main",
        "bundesland": "Hessen",
        "telefon": "+49 69 6606-0",
        "email": "info@gkk.de",
        "website": "www.gkk.de",
        "branche": "Wirtschaftsprüfung / Steuerberatung",
    },
    "Clariant Produkte (Deutschland) GmbH": {
        "adresse": "Am Unisys-Park 1, 65843 Sulzbach am Taunus",
        "plz": "65843",
        "stadt": "Sulzbach am Taunus",
        "bundesland": "Hessen",
        "telefon": "+49 6196 757-0",
        "email": "info@clariant.com",
        "website": "www.clariant.com",
        "branche": "Spezialchemie",
    },
}

def generate_employer_id(name, index):
    """Generate a unique employer ID based on name and index."""
    clean = re.sub(r'[^a-zA-ZäöüÄÖÜß]', '', name.lower())
    hash_part = hashlib.md5(clean.encode()).hexdigest()[:6].upper()
    return f"DE-{hash_part}-{index:04d}"

def search_company_info(company_name, delay=3):
    """Search for company contact information using web search CLI."""
    try:
        result = subprocess.run(
            ['z-ai', 'function', '-n', 'web_search',
             '-a', json.dumps({"query": f"{company_name} Impressum Kontakt Adresse Telefon", "num": 3})],
            capture_output=True, text=True, timeout=30
        )
        if result.returncode == 0 and result.stdout:
            # Parse the output
            try:
                data = json.loads(result.stdout)
                return data
            except:
                return None
        time.sleep(delay)
    except Exception as e:
        print(f"Error searching for {company_name}: {e}")
    return None

def extract_contact_from_search(company_name, search_results):
    """Try to extract contact info from search results."""
    info = {}
    if not search_results:
        return info
    
    for result in search_results:
        snippet = result.get('snippet', '')
        # Try to extract phone
        phone_match = re.search(r'(?:Tel|Telefon|Phone)[:\s]*([\+\d\s\-\(\)]{8,20})', snippet)
        if phone_match:
            info['telefon'] = phone_match.group(1).strip()
        # Try to extract email
        email_match = re.search(r'[\w\.-]+@[\w\.-]+\.\w+', snippet)
        if email_match:
            info['email'] = email_match.group(0)
        # Try to extract address
        addr_match = re.search(r'(\d{5}\s+[A-ZÄÖÜ][a-zäöüß]+(?:\s[a-zäöüß]+)*,\s*[\w\s\-\.]+(?:straße|str\.|weg|platz|allee|ring|damm|gasse|park|ufer|stieg))', snippet)
        if addr_match:
            info['adresse'] = addr_match.group(0)
    
    return info

def build_employer_data():
    """Build complete employer data with contact information."""
    all_contacts = {**KNOWN_CONTACTS, **ADDITIONAL_CONTACTS}
    employers_data = []
    
    seen_names = set()
    for idx, name in enumerate(EMPLOYERS, 1):
        # Deduplication
        normalized = name.lower().strip()
        if normalized in seen_names:
            continue
        seen_names.add(normalized)
        
        # Get contact info
        contact = all_contacts.get(name, {})
        
        employer = {
            'arbeitgeber_id': generate_employer_id(name, idx),
            'name': name,
            'adresse': contact.get('adresse', ''),
            'plz': contact.get('plz', ''),
            'stadt': contact.get('stadt', ''),
            'bundesland': contact.get('bundesland', ''),
            'telefon': contact.get('telefon', ''),
            'email': contact.get('email', ''),
            'website': contact.get('website', ''),
            'branche': contact.get('branche', ''),
            'quelle': 'berufsstart.de Top 100 / Web-Recherche',
        }
        employers_data.append(employer)
    
    return employers_data

if __name__ == '__main__':
    data = build_employer_data()
    # Save to JSON for the Excel creation step
    with open('/home/z/my-project/employers_data.json', 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    print(f"Collected data for {len(data)} employers")
    # Count how many have complete contact info
    complete = sum(1 for e in data if e['adresse'] and e['telefon'] and e['email'])
    print(f"Complete contact info: {complete}/{len(data)}")
